<a href="https://colab.research.google.com/github/HarshaR99/Python-Programs/blob/master/TensorFlow_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf

TensorFlow 2.x selected.


<tf.Tensor: shape=(), dtype=int32, numpy=2>

#Rank of Tensor
The highest degree of nested list is the rank of the tensor.In the below example there is an array3 which lies in an array2 which is nested array inside array1. I guess we should have uniform number of elements in each nested array here in a tensor, like I cannot have a single element in array3. 

In [17]:
rank1_tensor = tf.Variable([ [ ["Test",'ja'],["Test",'ja'] ],[ ["Test",'ja'],['Hello','jp'] ],[ ["Test",'ja'], ['ikl','ha']]], tf.string)
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

#Shape of tensor
A shape tells us the number of items we have in each dimension

In [18]:
rank1_tensor.shape

TensorShape([3, 2, 2])

The shape is 3,2,2 possibly beacuse there are 3 arrays of type array2 each with two array of type array 3 which in turn contain 3 elements.
Note that there are 3 values for shape as there are 3 layers of nested arrays as the tensor variable.

In [19]:
shape_tensor = tf.Variable([ [ ["Test"],["Test"] ],[ ["Test"],['Hello'] ],[ ["Test"], ['ikl']]], tf.string)
shape_tensor.shape

TensorShape([3, 2, 1])

The shape of this tensor is 3,2,1 possibly beacuse there 3 arrays of type array2, where each of them contain 2 arrays of type array3 , and each array3 contains 1 element each.

Reshaping tensors : an example 
Here we create a variable filled with 1's which have shape of 1,2,3 and then
reshape them to 2,3,1
# The numer of elements in the reshaped tensor MUST match the number in the original

In [29]:
tensor1 = tf.ones([1,2,3])
print('tensor1')
print(tensor1)
print('tensor2')
tensor2 = tf.reshape(tensor1,[2,3,1])
print(tensor2)
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3,2]
print('tensor3')
print(tensor3)                                      

tensor1
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tensor2
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tensor3
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


#Types of Tensors
1. Variable
2. Constant
3. Placeholder
4. SparseTensor

Except Variable all other types of tensors are immutable